# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: backend
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    profiles:
      - ''
      - prod
  redis:
    extends:
      file: ./redis.yml
      service: redis
