server:
  port: 8080

proxy-target:
  base-url: "http://192.168.194.250:8080/api"

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: proxy-consumer-group
  topic:
    eventos: eventos